FORMAT: 1A
HOST: https://api.example.com

# Rails API Starter

Welcome to the documentation of your API built with [Rails API Starter](https://github.com/alessandro1997/rails-api-starter).

Open `doc/index.apib` to start editing this document!

<!-- include(pings.apib) -->
<!-- include(tokens.apib) -->
