# Group Pings

## Ping collection [/pings]

### Creating a new ping [POST]

Creates a new ping request.

#### Request arguments

Argument   | Type     | Required? | Description
---------- | -------- | --------- | -----------------------------------
_message_  | _string_ | Yes       | A message for the server to return.

+ Request (application/json)
  + Body

            {
              "message": "lorem ipsum"
            }

+ Response 200 (application/json)
  + Body

            {
              "message": "lorem ipsum"
            }

+ Response 422 (application/json)
  + Body

            {
              "error_type": "missing_message",
              "error_message": "You must include a 'message' property in your ping request."
            }
